name: howzatt
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.4.0
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1
  bloc_concurrency: 0.2.0
  equatable: 2.0.3
  dio: ^4.0.4
  shared_preferences: 2.0.13
  json_annotation: 4.4.0
  formz: ^0.4.1
  stylish_dialog: ^0.1.2
  get: ^4.6.3
  get_it: ^7.2.0
  fluttertoast: 8.0.9
  http: 0.13.4
  flutter_countdown_timer: any
  modal_bottom_sheet: ^2.0.1
  intl: 0.17.0
  progress_indicators: 1.0.0
  paytm_allinonesdk: 1.1.7
  share_plus: 4.0.8
  jiffy: 5.0.0
  firebase_messaging: 11.4.2
  firebase_core: 1.18.0
  flutter_local_notifications: 9.6.1
  cashfree_pg: 2.0.10+30
  file_picker: 4.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/howzattlogo.png
    - assets/images/leftarrow.png
    - assets/images/loginpagephone.png
    - assets/images/verifyotp.png
    - assets/images/home.png
    - assets/images/verifyotp.png
    - assets/images/mymatches.png
    - assets/images/crypto.png
    - assets/images/portfolio.png
    - assets/images/userprofile.png
    - assets/images/cricket.png
    - assets/images/profileimage_one.png
    - assets/images/mybalance.png
    - assets/images/joystick.png
    - assets/images/leader_board.png
    - assets/images/settings.png
    - assets/images/inviteearn.png
    - assets/images/mynetwork.png
    - assets/images/help_desk.png
    - assets/images/faq.png
    - assets/images/privacypolicy.png
    - assets/images/terms&conditions.png
    - assets/images/back_arrow.png
    - assets/images/view_challenge.png
    - assets/images/down_arrow.png
    - assets/images/addmore.png
    - assets/images/homeuser.png
    - assets/images/homenotification.png
    - assets/images/homewallet.png
    - assets/images/football.png
    - assets/images/delhidevils.png
    - assets/images/trophy.png
    - assets/images/tshirt.png
    - assets/images/movie.png
    - assets/images/rupee_indian.png
    - assets/images/wifi_signal.png
    - assets/images/fast_forward.png
    - assets/images/bonus.png
    - assets/images/prize.png
    - assets/images/entry.png
    - assets/images/guarantee.png
    - assets/images/gold_medal.png
    - assets/images/wallet.png
    - assets/images/letter_m.png
    - assets/images/prizetrophy.png
    - assets/images/first.png
    - assets/images/check.png
    - assets/images/filter.png
    - assets/images/add.png
    - assets/images/downarrowtwo.png
    - assets/images/edit.png
    - assets/images/data_copy.png
    - assets/images/previewbackground.png
    - assets/images/market.png
    - assets/images/order.png
    - assets/images/pricealerts.png
    - assets/images/cryptocurrency.jpeg
    - assets/images/bitcoin.png
    - assets/images/ethereum.png
    - assets/images/tron.png
    - assets/images/chat.png
    - assets/images/arrow_up.png
    - assets/images/notification.png
    - assets/images/delete.png
    - assets/images/briefcase.png
    - assets/images/buybitcoin.png
    - assets/images/right_arrow.png
    - assets/images/account.png
    - assets/images/profilepricealerts.png
    - assets/images/profileinviteearn.png
    - assets/images/profilemymatches.png
    - assets/images/about.png
    - assets/images/customersupport.png
    - assets/images/bank_account.png
    - assets/images/upload_arrow.png
    - assets/images/rupee_symbol.png
    - assets/images/withdrawal.png
    - assets/images/minus.png
    - assets/images/eye.png
    - assets/images/datanotfound.png
    - assets/images/logout.png
    - assets/images/bowler.png
    - assets/images/batsman.png
    - assets/images/wicketkeeper.png
    - assets/images/allrounder.png
    - assets/images/htp1.png
    - assets/images/htp2.png
    - assets/images/htp3.png
    - assets/images/sliderimage1.png
    - assets/images/sliderimage2.png
    - assets/images/sliderimage3.png
    - assets/images/up_arrow.png
    - assets/images/pricealertadd.png
    - assets/images/referandearn.png


  fonts:
    - family: RoBlack
      fonts:
         - asset: assets/fonts/Roboto-Black.ttf
    - family: RoBlackItalic
      fonts:
            - asset: assets/fonts/Roboto-BlackItalic.ttf
    - family: RoBold
      fonts:
            - asset: assets/fonts/Roboto-Bold.ttf
    - family: RoBoldItalic
      fonts:
            - asset: assets/fonts/Roboto-BoldItalic.ttf
    - family: RoItalic
      fonts:
            - asset: assets/fonts/Roboto-Italic.ttf
    - family: RoLight
      fonts:
            - asset: assets/fonts/Roboto-Light.ttf
    - family: RoLightItalic
      fonts:
            - asset: assets/fonts/Roboto-LightItalic.ttf
    - family: RoMedium
      fonts:
            - asset: assets/fonts/Roboto-Medium.ttf
    - family: RoMediumItalic
      fonts:
            - asset: assets/fonts/Roboto-MediumItalic.ttf
    - family: RoRegular
      fonts:
            - asset: assets/fonts/Roboto-Regular.ttf
    - family: RoThin
      fonts:
            - asset: assets/fonts/Roboto-Thin.ttf
    - family: RoThinItalic
      fonts:
            - asset: assets/fonts/Roboto-ThinItalic.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
